# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ru:
  languageCode: ru-Latn
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/ru

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: Sergei Pavliuchenkov' blog
  params:
    description: A blog about anything 
  menu:
    main:
      - name: serapshi
        url: '#about'
        weight: 1
