defaultContentLanguage: ru
defaultContentLanguageInSubdir: true
languages:
  ru:
    contentDir: content/ru
    disabled: false
    languageCode: ru-Latn
    languageDirection: ltr
    languageName: Русский
    params:
      subtitle: Справочники, учебники и пояснения
    title: Проектная документация
    weight: 1
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Reference, Tutorials, and Explanations
    title: Project Documentation
    weight: 2